### Variables

@URL = http://localhost:3002/api/users

### 닉네임 변경
### onSuccess: {"ok": true}
### onError:
### -

PATCH  {{URL}}/nickname
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidGVzdDQiLCJpYXQiOjE2NjkzMTY2OTEsImV4cCI6MTY2OTMxODQ5MX0.oucWQCRrpySNGp9E2VotkKaP5frpiyH-mlqT7ECBsWs
Refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiIiwiaWF0IjoxNjY5MzE2NjkxLCJleHAiOjE2NjkzMjc0OTF9.Thf3mN1omtvgxyYY0HoOZp4bm5mqjTvwEuohr1FaZB8
Content-Type: application/json

{
    "nickname": "바뀐 닉네임"
}
